server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luciano-ferretto/microservices-java.git
          default-label: main
          search-paths:
          - 'configs/{application}'
          #username: teste
          #password: teste